-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR,
MONTH(SALES_DATE) MONTH,
COUNT(DISTINCT B.USER_ID) PUCRHASED_USERS,
ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PURCHASED_RATIO
FROM USER_INFO A INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE YEAR(JOINED) = '2021' AND YEAR(SALES_DATE) = '2022'
GROUP BY YEAR, MONTH
ORDER BY 1, 2