-- 자동차 종류가 '트럭'인 대여기록 중
-- 대여 id, 대여 금액 목록
-- 대여금액 내림차순, 대여 id 내림차순

WITH DC AS (
    SELECT REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+', '') AS MIN_DAYS, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
), RENTAL AS (
    SELECT HISTORY_ID, CAR.CAR_ID, CAR_TYPE, (DATEDIFF(END_DATE, START_DATE) + 1) AS DAYS, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR
    ON HISTORY.CAR_ID = CAR.CAR_ID
    WHERE CAR_TYPE = '트럭'
    ORDER BY HISTORY_ID
), DCC AS (
    SELECT HISTORY_ID, DAYS, DAILY_FEE, MAX(IF(DAYS >= MIN_DAYS, DISCOUNT_RATE, NULL)) AS DISCOUNT
    FROM RENTAL, DC
    GROUP BY HISTORY_ID
)
SELECT HISTORY_ID, IF(DISCOUNT IS NOT NULL, CONVERT(DAYS*DAILY_FEE*(100-DISCOUNT)*0.01, UNSIGNED), DAYS*DAILY_FEE) FEE
FROM DCC
ORDER BY FEE DESC, HISTORY_ID DESC

# SELECT DISTINCT HISTORY_ID,
# CONVERT(IFNULL(A.DAILY_FEE * 0.01 * (DATEDIFF(END_DATE, START_DATE) + 1) * (100 -
# (SELECT DISCOUNT_RATE
#  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#  WHERE CAR_TYPE = A.CAR_TYPE
#  AND DATEDIFF(END_DATE, START_DATE) + 1 > CONVERT(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+', ''), UNSIGNED)
#  ORDER BY DURATION_TYPE DESC
#  LIMIT 1)),
#                A.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)), UNSIGNED) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS A INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
# INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, HISTORY_ID DESC